# Site settings
title: Yash Agrawal
email: yashagmoguls@gmail.com
description: Undergrad at MIT, Manipal\ Expected 2021
baseurl: "/personal-website" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url: 
github_url: https://github.com/ingenuo-yag/
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://github.com/ingenuo-yag/
pinterest_url:
slack_url: https://github.com/ingenuo-yag/
twitter_url: https://github.com/ingenuo-yag/

# Build settings
markdown: kramdown

sass:
style: compressed
